### ISSUE TITLE
Cadastrar usuário

### ISSUE THREAD

**Issue by lilialnas** [Denils0n/Veganologo#6]
COMO futuro usuário do sistema => ator do sistema
QUERO realizar meu auto cadastro com login do Google/Facebook => descrição básica da funcionalidade
PARA acompanhar receitas veganas. => finalidade

- [ ] Mecanismo de autenticação/cadastro via rede sociais

- [ ]  Opcionalmente, permitir que o usuário se cadastre sem ter conta em rede social

- [ ]  Adicionar mecanismo de capctha
- [ ] prototipação de tela
- [ ]  backend
- [ ] frontend

**Comment by Denils0n** [comment]
Eu vou fazer isso :)
