### ISSUE TITLE
Cadastrar receitas

### ISSUE THREAD

**Issue by Denils0n** [Denils0n/Veganologo#7]
COMO futuro usuário do sistema => ator do sistema
QUERO realizar cadastro de receitas  => descrição básica da funcionalidade
PARA adicionar receitas => finalidade

- [ ]  Dividir as receitas por categorias
- [ ]  Criar pagina para o cadastro de receitas

**Comment by lilialnas** [comment]
@Denils0n boa!!!
Eu só faria um ressalva, nesse caso para cadastrar ou não, acredito que ele já deveria ser usuário do sistema.

Eu acredito que iremos precisar de um CRUD de categoria de receitas. Meus exemplos de categoria: gluten free, sugar free, baixa dificuldade, média dificuldade, alta dificuldade, pronta em menos de 30 min etc.

Fora isso: já pensa em como vai cadastrar os dados da receita? Quais são os subelementos que temos em uma receita?
Ingredientes, Passo a passo, tempo de forno, tempo de preparo, utensílios...

**Comment by PLuiza12** [comment]
Fiquei com essa parte.
